// Name: Federico Bustos
// Date: 6/12/2020
// Asg: Lab 3.5 Option 3
/* Desc: This program will display the total sales generated by the business in a particular month. As well as calculate 
   and display the state tax and local tax. The user will be prompted to input total sales, state tax, and local tax. */

#include <iostream>
#include <iomanip>    // For fixed, setprecision(), and showpoint

using namespace std;

int main()
{
	float totalSales,    // Declares the total sales
	      stateTax,      // Declares the state tax
	      localTax;      // Declares the local tax
	
	// Asks the user to input the total sales of the month
	cout << "Please input the total sales for the month." << endl;
	// User inputs the total sales into totalSales
	cin >> totalSales;
	
	// Asks the user to input the state tax in decimal form
	cout << "Please input the state tax percentage in decimal form. (.02 for 2%)" << endl;
	// User inputs the state tax into stateTax
	cin >> stateTax;
	
	// Asks the user to input the local tax in decimal form
	cout << "Please input the local tax percentage in decimal form. (.02 for 2%)" << endl;
	// User inputs the state tax into stateTax
	cin >> localTax;
	
	// Calculate the state tax
	stateTax *= totalSales;
	
	// Calculate the local tax
	localTax *= totalSales;
	
	//format the output
	cout << setprecision(2) << fixed << showpoint;
	
	//Display the total sales, state tax, and local tax
	cout << "The total sales for the month is $" << totalSales << endl
		 << "The state tax for the month is $" << stateTax << endl
		 << "The local tax for the month is $" << localTax << endl;
	
	return 0;
}
